CREATE TABLE IF NOT EXISTS Person
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      varchar(100) NOT NULL,
    year_of_birth int          NOT NULL,
    password      varchar      NOT NULL
);

INSERT INTO Person (username, year_of_birth, password)
VALUES ('Antony', 1959, 'f1a456ef1a6'),
       ('Terry', 1984, '564198231');